### ISSUE TITLE
Debian packaging

### ISSUE THREAD

**Issue by vranki** [otcshare/automotive-message-broker#47]
Debian packaging seems to be broken. It's at least missing compat file. I created one with "9" in it, but build still fails.
I'll try to fix this and possibly make a pull request. Tested on Ubuntu 14.10.

```
~/src/automotive-message-broker$ dpkg-buildpackage -rfakeroot -b
dpkg-buildpackage: source package automotive-message-broker
dpkg-buildpackage: source version 0.13.803
dpkg-buildpackage: source distribution utopic
dpkg-buildpackage: source changed by Kevron Rees <tripzero.kev@gmail.com>
dpkg-buildpackage: host architecture amd64
 dpkg-source --before-build automotive-message-broker
dpkg-source: warning: unknown information field 'Version' in input data in package's section of control info file
dpkg-source: warning: unknown information field 'Version' in input data in package's section of control info file
dpkg-source: warning: unknown information field 'Version' in input data in package's section of control info file
dpkg-source: warning: unknown information field 'Version' in input data in package's section of control info file
dpkg-source: warning: unknown information field 'Version' in input data in package's section of control info file
dpkg-source: warning: unknown information field 'Version' in input data in package's section of control info file
dpkg-source: warning: unknown information field 'Version' in input data in package's section of control info file
 fakeroot debian/rules clean
test -x debian/rules
rmdir obj-x86_64-linux-gnu
rmdir: failed to remove ‘obj-x86_64-linux-gnu’: No such file or directory
/usr/share/cdbs/1/rules/buildcore.mk:46: recipe for target 'cleanbuilddir' failed
make: [cleanbuilddir] Error 1 (ignored)
rm -f debian/stamp-makefile-build debian/stamp-makefile-install
/usr/bin/make  -C obj-x86_64-linux-gnu  -k clean
make[1]: *** obj-x86_64-linux-gnu: No such file or directory.  Stop.
/usr/share/cdbs/1/class/makefile.mk:55: recipe for target 'makefile-clean' failed
make: [makefile-clean] Error 2 (ignored)
rm -rf obj-x86_64-linux-gnu
dh_clean 
	rm -f debian/*.debhelper.log
	rm -f debian/files
	find .  \( \( -type f -a \
	        \( -name '#*#' -o -name '.*~' -o -name '*~' -o -name DEADJOE \
		 -o -name '*.orig' -o -name '*.rej' -o -name '*.bak' \
		 -o -name '.*.orig' -o -name .*.rej -o -name '.SUMS' \
		 -o -name TAGS -o \( -path '*/.deps/*' -a -name '*.P' \) \
		\) -exec rm -f {} + \) -o \
		\( -type d -a -name autom4te.cache -prune -exec rm -rf {} + \) \)
	rm -f *-stamp
 debian/rules build
make: Nothing to be done for 'build'.
 fakeroot debian/rules binary
make: Nothing to be done for 'binary'.
 dpkg-genchanges -b >../automotive-message-broker_0.13.803_amd64.changes
dpkg-genchanges: error: binary build with no binary artifacts found; cannot distribute
dpkg-buildpackage: error: dpkg-genchanges gave error exit status 2
```

**Comment by tripzero** [comment]
I typically use debuild instead of dpkg-buildpackage.  Did you ever make progress on this issue?

**Comment by vranki** [comment]
Nope, the same happens:

:~/src/automotive-message-broker$ debuild
 dpkg-buildpackage -rfakeroot -D -us -uc
dpkg-buildpackage: source package automotive-message-broker
dpkg-buildpackage: source version 0.13.803
dpkg-buildpackage: source distribution utopic
dpkg-buildpackage: source changed by Kevron Rees <tripzero.kev@gmail.com>
 dpkg-source --before-build automotive-message-broker
dpkg-buildpackage: host architecture amd64
dpkg-source: warning: unknown information field 'Version' in input data in package's section of control info file
dpkg-source: warning: unknown information field 'Version' in input data in package's section of control info file
dpkg-source: warning: unknown information field 'Version' in input data in package's section of control info file
dpkg-source: warning: unknown information field 'Version' in input data in package's section of control info file
dpkg-source: warning: unknown information field 'Version' in input data in package's section of control info file
dpkg-source: warning: unknown information field 'Version' in input data in package's section of control info file
dpkg-source: warning: unknown information field 'Version' in input data in package's section of control info file
 fakeroot debian/rules clean
test -x debian/rules
rmdir obj-x86_64-linux-gnu
rmdir: failed to remove ‘obj-x86_64-linux-gnu’: No such file or directory
/usr/share/cdbs/1/rules/buildcore.mk:46: recipe for target 'cleanbuilddir' failed
make: [cleanbuilddir] Error 1 (ignored)
rm -f debian/stamp-makefile-build debian/stamp-makefile-install
/usr/bin/make  -C obj-x86_64-linux-gnu  -k clean
make[1]: *** obj-x86_64-linux-gnu: No such file or directory.  Stop.
/usr/share/cdbs/1/class/makefile.mk:55: recipe for target 'makefile-clean' failed
make: [makefile-clean] Error 2 (ignored)
rm -rf obj-x86_64-linux-gnu
dh_clean 
	rm -f debian/*.debhelper.log
dh_clean: No compatibility level specified in debian/compat
dh_clean: This package will soon FTBFS; time to fix it!
dh_clean: Compatibility levels before 5 are deprecated (level 1 in use)
	rm -f debian/debhelper.log
	rm -f debian/files
	find .  \( \( -type f -a \
	        \( -name '#*#' -o -name '.*~' -o -name '*~' -o -name DEADJOE \
		 -o -name '*.orig' -o -name '*.rej' -o -name '*.bak' \
		 -o -name '.*.orig' -o -name .*.rej -o -name '.SUMS' \
		 -o -name TAGS -o \( -path '*/.deps/*' -a -name '*.P' \) \
		\) -exec rm -f {} + \) -o \
		\( -type d -a -name autom4te.cache -prune -exec rm -rf {} + \) \)
 dpkg-source -b automotive-message-broker
dpkg-source: warning: unknown information field 'Version' in input data in package's section of control info file
dpkg-source: warning: unknown information field 'Version' in input data in package's section of control info file
dpkg-source: warning: unknown information field 'Version' in input data in package's section of control info file
dpkg-source: warning: unknown information field 'Version' in input data in package's section of control info file
dpkg-source: warning: unknown information field 'Version' in input data in package's section of control info file
dpkg-source: warning: unknown information field 'Version' in input data in package's section of control info file
dpkg-source: warning: unknown information field 'Version' in input data in package's section of control info file
dpkg-source: warning: no source format specified in debian/source/format, see dpkg-source(1)
dpkg-source: warning: source directory 'automotive-message-broker' is not <sourcepackage>-<upstreamversion> 'automotive-message-broker-0.13.803'
dpkg-source: info: using source format `1.0'
dpkg-source: info: building automotive-message-broker in automotive-message-broker_0.13.803.tar.gz
dpkg-source: info: building automotive-message-broker in automotive-message-broker_0.13.803.dsc
 debian/rules build
make: Nothing to be done for 'build'.
 fakeroot debian/rules binary
make: Nothing to be done for 'binary'.
 dpkg-genchanges  >../automotive-message-broker_0.13.803_amd64.changes
dpkg-genchanges: error: binary build with no binary artifacts found; cannot distribute
dpkg-buildpackage: error: dpkg-genchanges gave error exit status 2
debuild: fatal error at line 1364:
dpkg-buildpackage -rfakeroot -D -us -uc failed

**Comment by tripzero** [comment]
It appears to build find on x86.  I can reproduce this on x86_64 however.
I think I know how to fix it.

**Comment by tripzero** [comment]
fixed with PR #49 (https://github.com/tripzero/automotive-message-broker/commit/0581c5cc39f210384de00d7e777b628c0cf10eda)

If you could pull in that patch and verify, it would be appreciated.

**Comment by vranki** [comment]
Yep, the build was succesful but debuild gave a lot of warnings which should be fixed. Also it would be good to have packaging instructions in README. I did cmake .., make and then debuild in the project directory. Most projects have just debian directory in the root and build just by running debuild.

**Comment by tripzero** [comment]
>> Also it would be good to have packaging instructions in README
+1
