### ISSUE TITLE
GLONASS Support

### ISSUE THREAD

**Issue by xentnex** [otcshare/automotive-message-broker#50]
Sometimes we see NMEA protocol messages  with GLONASS indicators. AMB should be capable of parsing GLONASS protocol messages... An example protocol message is shown below; 

$GNRMC,073121.00,A,5544.7049,N,03743.7405,E,000.02626,301.4,190312,,,A*47

**Comment by tripzero** [comment]
This looks familiar to the GPRMC message.  Do you know if GN* messages have extra information in them over typical GP* messages?

**Comment by xentnex** [comment]
It is same as the GPRMC. No extra information...

2015-03-26 18:38 GMT+02:00 Kevron Rees <notifications@github.com>:

**Comment by tripzero** [comment]
8eb33aa has GNRMC support.  I haven't tested it yet.  I'll have to see if any of my GPS/GLONASS devices produce that message.

**Comment by xentnex** [comment]
I've seen these messages on VTC 1010 with u-blox gps.

2015-03-27 9:07 GMT+02:00 Kevron Rees <notifications@github.com>:
