### ISSUE TITLE
Allow "no-value" as property values.

### ISSUE THREAD

**Issue by petr-nechaev** [otcshare/automotive-message-broker#51]
Plugins may need to report "no-value" for property when timeouts or other data losses occur. IVI software should be able to indicate that, for example, outside temperature sensor failed.

Current design doesn't allow setting of NULL because of static typecast in boost::any.

Even better way would be implementing something similar to Value-Time-Quality according to OPC (newer OPC UA) standard. It is proven by years of use in safety-critical projects.

Actually, OPC does something very similar to AMB and I, personally, would merge IEC 62541 OPC UA specs into our AMB implementation. Occam's razor. OPC UA has good binary and XML protocols. Data definition mechanisms are flexible enough to easily accommodate automotive concepts. OPC is designed to have high throughput and low latencies.
There is a hunt for open-source OPC UA implementation so AMB can get new contributors.

References:
[1] https://wikis.web.cern.ch/wikis/download/attachments/14778584/PVSS+usage+of+the+OPC+Item+Quality+Flag.pdf
[2] https://partners.iconics.com/%2FTech-Support%2FGENESIS64%2FGenesis64%2FApplication-Note%2FV10-7%2FICONICS-OPC-UA-Quality-Codes.aspx
[3] https://github.com/acplt/open62541/wiki/List-of-Open-Source-OPC-UA-Implementations

**Comment by petr-nechaev** [comment]
And one more architectural question, just as a discussion:
Should, by design, AMB be inter-operable with AUTOSAR stacks such as http://www.arccore.com/hg/arc-stable/ ?

**Comment by tripzero** [comment]
Inter-operability is usually a good thing.  Within GENIVI, there were talks of interoperability with autosar using the node link manager in an AMB source plugin.

**Comment by tripzero** [comment]
>>Plugins may need to report "no-value" for property when timeouts or other data losses occur. IVI software should be able to indicate that, for example, outside temperature sensor failed."

Agreed.  I think this is an area of improvement.  I wouldn't be opposed to adopting OPC UA quality codes to indicate the quality of the data.  That may be a simple addition to AbstractPropertyType.

>> OPC UA has good binary and XML protocols.

I wonder if we could use this as an AmbClient implementation in addition to JSON.  I'm very much interested in a fast binary protocol.

**Comment by tripzero** [comment]
version quality support in 0.15 should address this issue.
