### ISSUE TITLE
build issue with std c++11

### ISSUE THREAD

**Issue by slssun007** [otcshare/automotive-message-broker#62]
automotive-message-broker-master/lib/listplusplus.h:30:85: error: parameter declared ‘auto’
  return std::any_of(iteratable.begin(), iteratable.end(), [value, &comparator](auto i) { return comparator(value, i); });

**Comment by petr-nechaev** [comment]
You can try looking at https://github.com/otcshare/automotive-message-broker/commit/d4f0c746dc1d4dc9226f16b6bd463e7ef3c57994. My fix was:
https://github.com/CogentEmbedded/automotive-message-broker/commit/fb401094c3d88da14e1b909d786a86c3a68d2199

**Comment by tripzero** [comment]
"auto" inside lamdas is a c++14 feature.  0.14 uses the same style @petr-nechaev is using.  The bug may be not using -std=c++14.  I'll check.

**Comment by tripzero** [comment]
Looks like we are using -std=c++1y[1]. Your compiler may support some c++14 features, but perhaps is missing this one.  What version of gcc are you using?

[1] - https://github.com/otcshare/automotive-message-broker/blob/master/CMakeLists.txt#L55

**Comment by slssun007** [comment]
Thanks its working fine with petr-nechaev style.

**Comment by slssun007** [comment]
Thanks its working fine with petr-nechaev style.
