### ISSUE TITLE
A question about "VehicleCommonDataType" in amb.in.fidl

### ISSUE THREAD

**Issue by wenzhanchao** [otcshare/automotive-message-broker#72]
Recently, I'm studying the "automotive-message-broker", the branch is 0.13, I can't find the define of "VehicleCommonDataType" in amb.in.fidl, the source code:
interface IgnitionTime : VehicleCommonDataType {
   /*!
	* \brief MUST return time at ignition on
	*/
	attribute UInt64 ignitionOnTime readonly

	/*!
	 * \brief MUST return time at ignition off
	 */
	 attribute UInt64 ignitionOffTime readonly
}

        Can you tell me where the "VehicleCommonDataType" is define, and can you generate the code(Java or C++) from this fidl?

**Comment by tripzero** [comment]
Fixed with PR #73
