### ISSUE TITLE
Errors in pkgconfig file

### ISSUE THREAD

**Issue by again4you** [otcshare/automotive-message-broker#79]
Generated pkgconfig files(i.e. *.pc) have the wrong path as below.
Because of this reason, include files are not found when building AMB plugin module. 

```
$ cat /usr/local/lib/pkgconfig/amb-plugins-common.pc
prefix=/usr/local
exec_prefix=${prefix}
libdir=lib
includedir=include/amb
```

**Comment by tripzero** [comment]
fixed with PR #81
