### ISSUE TITLE
Wrong installation path for lib64

### ISSUE THREAD

**Issue by again4you** [otcshare/automotive-message-broker#82]
Generated CMakeLists.txt by AmbSignalMapper is always install the shared object into fixed path (i.e. lib/automotive-message-broker) even though it is built for 64bits environment. This is mainly because generated CMakeLists.txt uses fixed installation path like that.

`install(TARGETS ambtmpl_plugin LIBRARY DESTINATION "lib/automotive-message-broker")`

**Comment by tripzero** [comment]
fixed with PR #81
